


name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Run Docker compose command
      env:
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      
      run: docker compose -f docker/production-docker-compose.yaml -p tap-wallet-bot up --build -d --force-recreate
 
